[tool.setuptools.packages]
find = {}

[project]
name = "treescape"
version = "2026.1.0"
description = "Jupyter-based visualization tool for performance data"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]

[tool.poetry]
name = "treescape"
version = "2026.1.0"
description = "Jupyter-based visualization for performance data."
license = "MIT"

[tool.ruff]
line-length = 88
target-version = 'py311'
include = ['\.pyi?$']
exclude = [
  ".eggs",
  ".git",
  ".hg",
  ".mypy_cache",
  ".tox",
  ".venv",
  "_build",
  "buck-out",
  "build",
  "dist",
]

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
